# Generated by Django 3.1.4 on 2021-01-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributed_quest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='time_created',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time_started',
        ),
    ]
